=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RaptApiClient::BondedDeviceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'BondedDeviceApi' do
  before do
    # run before each test
    @api_instance = RaptApiClient::BondedDeviceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of BondedDeviceApi' do
    it 'should create an instance of BondedDeviceApi' do
      expect(@api_instance).to be_instance_of(RaptApiClient::BondedDeviceApi)
    end
  end

  # unit tests for api_bonded_devices_get_bonded_device_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :bonded_device_id 
  # @return [BondedDeviceModel]
  describe 'api_bonded_devices_get_bonded_device_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_bonded_devices_get_bonded_devices_get
  # @param [Hash] opts the optional parameters
  # @return [Array<BondedDeviceModel>]
  describe 'api_bonded_devices_get_bonded_devices_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_bonded_devices_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :bonded_device_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [Array<BondedDeviceTelemetryModel>]
  describe 'api_bonded_devices_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
