=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RaptApiClient::CanFillerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'CanFillerApi' do
  before do
    # run before each test
    @api_instance = RaptApiClient::CanFillerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CanFillerApi' do
    it 'should create an instance of CanFillerApi' do
      expect(@api_instance).to be_instance_of(RaptApiClient::CanFillerApi)
    end
  end

  # unit tests for api_can_fillers_get_can_filler_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :can_filler_id 
  # @return [CanFillerModel]
  describe 'api_can_fillers_get_can_filler_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_can_fillers_get_can_fillers_get
  # @param [Hash] opts the optional parameters
  # @return [Array<CanFillerModel>]
  describe 'api_can_fillers_get_can_fillers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_can_fillers_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :can_filler_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [Array<CanFillerTelemetryModel>]
  describe 'api_can_fillers_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
