=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ExternalDeviceApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ExternalDeviceApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ExternalDeviceApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ExternalDeviceApi' do
    it 'should create an instance of ExternalDeviceApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ExternalDeviceApi)
    end
  end

  # unit tests for api_external_devices_get_all_get
  # @param [Hash] opts the optional parameters
  # @return [Array<ExternalDeviceModel>]
  describe 'api_external_devices_get_all_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_external_devices_get_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :device_id 
  # @return [ExternalDeviceModel]
  describe 'api_external_devices_get_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_external_devices_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :device_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [Array<ExternalDeviceTelemetryModel>]
  describe 'api_external_devices_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_external_devices_telemetry_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :device_id 
  # @option opts [Object] :body 
  # @return [nil]
  describe 'api_external_devices_telemetry_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
