=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RaptApiClient::HydrometerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'HydrometerApi' do
  before do
    # run before each test
    @api_instance = RaptApiClient::HydrometerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of HydrometerApi' do
    it 'should create an instance of HydrometerApi' do
      expect(@api_instance).to be_instance_of(RaptApiClient::HydrometerApi)
    end
  end

  # unit tests for api_hydrometers_get_hydrometer_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :hydrometer_id 
  # @return [HydrometerModel]
  describe 'api_hydrometers_get_hydrometer_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_hydrometers_get_hydrometers_get
  # @param [Hash] opts the optional parameters
  # @return [Array<HydrometerModel>]
  describe 'api_hydrometers_get_hydrometers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_hydrometers_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :hydrometer_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [Array<HydrometerTelemetryModel>]
  describe 'api_hydrometers_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
