=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::ProfileTypeApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'ProfileTypeApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::ProfileTypeApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProfileTypeApi' do
    it 'should create an instance of ProfileTypeApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::ProfileTypeApi)
    end
  end

  # unit tests for api_profile_types_get_all_get
  # @param [Hash] opts the optional parameters
  # @return [Array<ProfileModel>]
  describe 'api_profile_types_get_all_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_profile_types_get_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :id 
  # @return [ProfileTypeModel]
  describe 'api_profile_types_get_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
