=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RaptApiClient::StillApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'StillApi' do
  before do
    # run before each test
    @api_instance = RaptApiClient::StillApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of StillApi' do
    it 'should create an instance of StillApi' do
      expect(@api_instance).to be_instance_of(RaptApiClient::StillApi)
    end
  end

  # unit tests for api_stills_get_still_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @return [StillModel]
  describe 'api_stills_get_still_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_get_stills_get
  # @param [Hash] opts the optional parameters
  # @return [Array<StillModel>]
  describe 'api_stills_get_stills_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @option opts [String] :profile_session_id 
  # @return [Array<StillTelemetryModel>]
  describe 'api_stills_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_heating_enabled_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Boolean] :state 
  # @return [Boolean]
  describe 'api_stills_set_heating_enabled_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_heating_utilisation_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Float] :utilisation 
  # @return [Boolean]
  describe 'api_stills_set_heating_utilisation_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_pid_enabled_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Boolean] :state 
  # @return [Boolean]
  describe 'api_stills_set_pid_enabled_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_pid_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Float] :p 
  # @option opts [Float] :i 
  # @option opts [Float] :d 
  # @return [Boolean]
  describe 'api_stills_set_pid_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_pump_enabled_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Boolean] :state 
  # @return [Boolean]
  describe 'api_stills_set_pump_enabled_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_pump_utilisation_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Float] :utilisation 
  # @return [Boolean]
  describe 'api_stills_set_pump_utilisation_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_stills_set_target_temperature_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :still_id 
  # @option opts [Float] :target 
  # @return [Boolean]
  describe 'api_stills_set_target_temperature_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
