=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'

# Unit tests for RaptApiClient::TemperatureControllerApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'TemperatureControllerApi' do
  before do
    # run before each test
    @api_instance = RaptApiClient::TemperatureControllerApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of TemperatureControllerApi' do
    it 'should create an instance of TemperatureControllerApi' do
      expect(@api_instance).to be_instance_of(RaptApiClient::TemperatureControllerApi)
    end
  end

  # unit tests for api_temperature_controllers_get_telemetry_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :temperature_controller_id 
  # @option opts [Time] :start_date 
  # @option opts [Time] :end_date 
  # @return [Array<TemperatureControllerTelemetryModel>]
  describe 'api_temperature_controllers_get_telemetry_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_temperature_controllers_get_temperature_controller_get
  # @param [Hash] opts the optional parameters
  # @option opts [String] :temperature_controller_id 
  # @return [TemperatureControllerModel]
  describe 'api_temperature_controllers_get_temperature_controller_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_temperature_controllers_get_temperature_controllers_get
  # @param [Hash] opts the optional parameters
  # @return [Array<TemperatureControllerModel>]
  describe 'api_temperature_controllers_get_temperature_controllers_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_temperature_controllers_set_pid_enabled_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :temperature_controller_id 
  # @option opts [Boolean] :state 
  # @return [Boolean]
  describe 'api_temperature_controllers_set_pid_enabled_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_temperature_controllers_set_pid_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :temperature_controller_id 
  # @option opts [Float] :p 
  # @option opts [Float] :i 
  # @option opts [Float] :d 
  # @return [Boolean]
  describe 'api_temperature_controllers_set_pid_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

  # unit tests for api_temperature_controllers_set_target_temperature_post
  # @param [Hash] opts the optional parameters
  # @option opts [String] :temperature_controller_id 
  # @option opts [Float] :target 
  # @return [Boolean]
  describe 'api_temperature_controllers_set_target_temperature_post test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
