=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RaptApiClient::ProfileValueOperatorsNullable
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RaptApiClient::ProfileValueOperatorsNullable do
  #let(:instance) { RaptApiClient::ProfileValueOperatorsNullable.new }

  describe 'test an instance of ProfileValueOperatorsNullable' do
    it 'should create an instance of ProfileValueOperatorsNullable' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RaptApiClient::ProfileValueOperatorsNullable)
    end
  end

end
