=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for OpenapiClient::ProfileStepEndTypes
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe OpenapiClient::ProfileStepEndTypes do
  let(:instance) { OpenapiClient::ProfileStepEndTypes.new }

  describe 'test an instance of ProfileStepEndTypes' do
    it 'should create an instance of ProfileStepEndTypes' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(OpenapiClient::ProfileStepEndTypes)
    end
  end

end
