=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for RaptApiClient::ProfileValueOperators
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe RaptApiClient::ProfileValueOperators do
  let(:instance) { RaptApiClient::ProfileValueOperators.new }

  describe 'test an instance of ProfileValueOperators' do
    it 'should create an instance of ProfileValueOperators' do
      # uncomment below to test the instance creation
      #expect(instance).to be_instance_of(RaptApiClient::ProfileValueOperators)
    end
  end

end
