=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module RaptApiClient
  class ProfileStepControlTypes
    TARGET = "Target".freeze
    RAMP = "Ramp".freeze
    FREE_RISE = "FreeRise".freeze

    def self.all_vars
      @all_vars ||= [TARGET, RAMP, FREE_RISE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ProfileStepControlTypes.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ProfileStepControlTypes"
    end
  end
end
