=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module RaptApiClient
  class StillTelemetryModel < ApiModelBase
    attr_accessor :id

    attr_accessor :row_key

    attr_accessor :created_on

    attr_accessor :mac_address

    attr_accessor :rssi

    attr_accessor :control_device_type

    attr_accessor :control_device_mac_address

    attr_accessor :control_device_temperature

    attr_accessor :temperature

    attr_accessor :temperature_vapour

    attr_accessor :temperature_wash

    attr_accessor :target_temperature

    attr_accessor :rhc

    attr_accessor :ethanol

    attr_accessor :total_run_time

    attr_accessor :heating_run_time

    attr_accessor :heating_starts

    attr_accessor :power

    attr_accessor :abv

    attr_accessor :temp_per_min

    attr_accessor :profile_id

    attr_accessor :profile_step_id

    attr_accessor :profile_session_start_date

    attr_accessor :profile_session_time

    attr_accessor :profile_step_progress

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'row_key' => :'rowKey',
        :'created_on' => :'createdOn',
        :'mac_address' => :'macAddress',
        :'rssi' => :'rssi',
        :'control_device_type' => :'controlDeviceType',
        :'control_device_mac_address' => :'controlDeviceMacAddress',
        :'control_device_temperature' => :'controlDeviceTemperature',
        :'temperature' => :'temperature',
        :'temperature_vapour' => :'temperatureVapour',
        :'temperature_wash' => :'temperatureWash',
        :'target_temperature' => :'targetTemperature',
        :'rhc' => :'rhc',
        :'ethanol' => :'ethanol',
        :'total_run_time' => :'totalRunTime',
        :'heating_run_time' => :'heatingRunTime',
        :'heating_starts' => :'heatingStarts',
        :'power' => :'power',
        :'abv' => :'abv',
        :'temp_per_min' => :'tempPerMin',
        :'profile_id' => :'profileId',
        :'profile_step_id' => :'profileStepId',
        :'profile_session_start_date' => :'profileSessionStartDate',
        :'profile_session_time' => :'profileSessionTime',
        :'profile_step_progress' => :'profileStepProgress'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'row_key' => :'String',
        :'created_on' => :'Time',
        :'mac_address' => :'String',
        :'rssi' => :'Float',
        :'control_device_type' => :'String',
        :'control_device_mac_address' => :'String',
        :'control_device_temperature' => :'Float',
        :'temperature' => :'Float',
        :'temperature_vapour' => :'Float',
        :'temperature_wash' => :'Float',
        :'target_temperature' => :'Float',
        :'rhc' => :'Float',
        :'ethanol' => :'Integer',
        :'total_run_time' => :'Float',
        :'heating_run_time' => :'Float',
        :'heating_starts' => :'Float',
        :'power' => :'Float',
        :'abv' => :'Float',
        :'temp_per_min' => :'Float',
        :'profile_id' => :'String',
        :'profile_step_id' => :'String',
        :'profile_session_start_date' => :'Time',
        :'profile_session_time' => :'Integer',
        :'profile_step_progress' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'row_key',
        :'mac_address',
        :'control_device_type',
        :'control_device_mac_address',
        :'control_device_temperature',
        :'temperature_vapour',
        :'temperature_wash',
        :'target_temperature',
        :'rhc',
        :'ethanol',
        :'power',
        :'abv',
        :'temp_per_min',
        :'profile_id',
        :'profile_step_id',
        :'profile_session_start_date',
        :'profile_session_time',
        :'profile_step_progress'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RaptApiClient::StillTelemetryModel` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RaptApiClient::StillTelemetryModel`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'row_key')
        self.row_key = attributes[:'row_key']
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

      if attributes.key?(:'mac_address')
        self.mac_address = attributes[:'mac_address']
      end

      if attributes.key?(:'rssi')
        self.rssi = attributes[:'rssi']
      end

      if attributes.key?(:'control_device_type')
        self.control_device_type = attributes[:'control_device_type']
      end

      if attributes.key?(:'control_device_mac_address')
        self.control_device_mac_address = attributes[:'control_device_mac_address']
      end

      if attributes.key?(:'control_device_temperature')
        self.control_device_temperature = attributes[:'control_device_temperature']
      end

      if attributes.key?(:'temperature')
        self.temperature = attributes[:'temperature']
      end

      if attributes.key?(:'temperature_vapour')
        self.temperature_vapour = attributes[:'temperature_vapour']
      end

      if attributes.key?(:'temperature_wash')
        self.temperature_wash = attributes[:'temperature_wash']
      end

      if attributes.key?(:'target_temperature')
        self.target_temperature = attributes[:'target_temperature']
      end

      if attributes.key?(:'rhc')
        self.rhc = attributes[:'rhc']
      end

      if attributes.key?(:'ethanol')
        self.ethanol = attributes[:'ethanol']
      end

      if attributes.key?(:'total_run_time')
        self.total_run_time = attributes[:'total_run_time']
      end

      if attributes.key?(:'heating_run_time')
        self.heating_run_time = attributes[:'heating_run_time']
      end

      if attributes.key?(:'heating_starts')
        self.heating_starts = attributes[:'heating_starts']
      end

      if attributes.key?(:'power')
        self.power = attributes[:'power']
      end

      if attributes.key?(:'abv')
        self.abv = attributes[:'abv']
      end

      if attributes.key?(:'temp_per_min')
        self.temp_per_min = attributes[:'temp_per_min']
      end

      if attributes.key?(:'profile_id')
        self.profile_id = attributes[:'profile_id']
      end

      if attributes.key?(:'profile_step_id')
        self.profile_step_id = attributes[:'profile_step_id']
      end

      if attributes.key?(:'profile_session_start_date')
        self.profile_session_start_date = attributes[:'profile_session_start_date']
      end

      if attributes.key?(:'profile_session_time')
        self.profile_session_time = attributes[:'profile_session_time']
      end

      if attributes.key?(:'profile_step_progress')
        self.profile_step_progress = attributes[:'profile_step_progress']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          row_key == o.row_key &&
          created_on == o.created_on &&
          mac_address == o.mac_address &&
          rssi == o.rssi &&
          control_device_type == o.control_device_type &&
          control_device_mac_address == o.control_device_mac_address &&
          control_device_temperature == o.control_device_temperature &&
          temperature == o.temperature &&
          temperature_vapour == o.temperature_vapour &&
          temperature_wash == o.temperature_wash &&
          target_temperature == o.target_temperature &&
          rhc == o.rhc &&
          ethanol == o.ethanol &&
          total_run_time == o.total_run_time &&
          heating_run_time == o.heating_run_time &&
          heating_starts == o.heating_starts &&
          power == o.power &&
          abv == o.abv &&
          temp_per_min == o.temp_per_min &&
          profile_id == o.profile_id &&
          profile_step_id == o.profile_step_id &&
          profile_session_start_date == o.profile_session_start_date &&
          profile_session_time == o.profile_session_time &&
          profile_step_progress == o.profile_step_progress
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, row_key, created_on, mac_address, rssi, control_device_type, control_device_mac_address, control_device_temperature, temperature, temperature_vapour, temperature_wash, target_temperature, rhc, ethanol, total_run_time, heating_run_time, heating_starts, power, abv, temp_per_min, profile_id, profile_step_id, profile_session_start_date, profile_session_time, profile_step_progress].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
