=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'date'
require 'time'

module RaptApiClient
  class ToggleStates
    ALWAYS_ON = "AlwaysOn".freeze
    ALWAYS_OFF = "AlwaysOff".freeze
    AUTOMATIC = "Automatic".freeze

    def self.all_vars
      @all_vars ||= [ALWAYS_ON, ALWAYS_OFF, AUTOMATIC].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if ToggleStates.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #ToggleStates"
    end
  end
end
