=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.20.0

=end

require 'date'
require 'time'

module RaptApiClient
  class YeastModel < ApiModelBase
    attr_accessor :id

    attr_accessor :deleted

    attr_accessor :created_on

    attr_accessor :created_by

    attr_accessor :modified_on

    attr_accessor :modified_by

    attr_accessor :name

    attr_accessor :product_id

    attr_accessor :laboratory

    attr_accessor :supplier

    attr_accessor :kegland_product_code

    attr_accessor :type

    attr_accessor :form

    attr_accessor :min_temperature

    attr_accessor :max_temperature

    attr_accessor :flocculation

    attr_accessor :attenuation

    attr_accessor :notes

    attr_accessor :best_for

    attr_accessor :max_reuse

    attr_accessor :add_to_secondary

    attr_accessor :amount_type

    attr_accessor :inventory_amount

    attr_accessor :archived

    attr_accessor :stock_level

    attr_accessor :global_yeast_id

    attr_accessor :is_global

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'deleted' => :'deleted',
        :'created_on' => :'createdOn',
        :'created_by' => :'createdBy',
        :'modified_on' => :'modifiedOn',
        :'modified_by' => :'modifiedBy',
        :'name' => :'name',
        :'product_id' => :'productId',
        :'laboratory' => :'laboratory',
        :'supplier' => :'supplier',
        :'kegland_product_code' => :'keglandProductCode',
        :'type' => :'type',
        :'form' => :'form',
        :'min_temperature' => :'minTemperature',
        :'max_temperature' => :'maxTemperature',
        :'flocculation' => :'flocculation',
        :'attenuation' => :'attenuation',
        :'notes' => :'notes',
        :'best_for' => :'bestFor',
        :'max_reuse' => :'maxReuse',
        :'add_to_secondary' => :'addToSecondary',
        :'amount_type' => :'amountType',
        :'inventory_amount' => :'inventoryAmount',
        :'archived' => :'archived',
        :'stock_level' => :'stockLevel',
        :'global_yeast_id' => :'globalYeastId',
        :'is_global' => :'isGlobal'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'deleted' => :'Boolean',
        :'created_on' => :'Time',
        :'created_by' => :'String',
        :'modified_on' => :'Time',
        :'modified_by' => :'String',
        :'name' => :'String',
        :'product_id' => :'String',
        :'laboratory' => :'String',
        :'supplier' => :'String',
        :'kegland_product_code' => :'String',
        :'type' => :'String',
        :'form' => :'String',
        :'min_temperature' => :'Float',
        :'max_temperature' => :'Float',
        :'flocculation' => :'String',
        :'attenuation' => :'Float',
        :'notes' => :'String',
        :'best_for' => :'String',
        :'max_reuse' => :'Integer',
        :'add_to_secondary' => :'Boolean',
        :'amount_type' => :'AmountTypes',
        :'inventory_amount' => :'Float',
        :'archived' => :'Boolean',
        :'stock_level' => :'Float',
        :'global_yeast_id' => :'String',
        :'is_global' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
        :'product_id',
        :'laboratory',
        :'supplier',
        :'kegland_product_code',
        :'type',
        :'form',
        :'flocculation',
        :'notes',
        :'best_for',
        :'inventory_amount',
        :'global_yeast_id',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `RaptApiClient::YeastModel` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `RaptApiClient::YeastModel`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      end

      if attributes.key?(:'deleted')
        self.deleted = attributes[:'deleted']
      end

      if attributes.key?(:'created_on')
        self.created_on = attributes[:'created_on']
      end

      if attributes.key?(:'created_by')
        self.created_by = attributes[:'created_by']
      end

      if attributes.key?(:'modified_on')
        self.modified_on = attributes[:'modified_on']
      end

      if attributes.key?(:'modified_by')
        self.modified_by = attributes[:'modified_by']
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'product_id')
        self.product_id = attributes[:'product_id']
      end

      if attributes.key?(:'laboratory')
        self.laboratory = attributes[:'laboratory']
      end

      if attributes.key?(:'supplier')
        self.supplier = attributes[:'supplier']
      end

      if attributes.key?(:'kegland_product_code')
        self.kegland_product_code = attributes[:'kegland_product_code']
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      end

      if attributes.key?(:'form')
        self.form = attributes[:'form']
      end

      if attributes.key?(:'min_temperature')
        self.min_temperature = attributes[:'min_temperature']
      end

      if attributes.key?(:'max_temperature')
        self.max_temperature = attributes[:'max_temperature']
      end

      if attributes.key?(:'flocculation')
        self.flocculation = attributes[:'flocculation']
      end

      if attributes.key?(:'attenuation')
        self.attenuation = attributes[:'attenuation']
      end

      if attributes.key?(:'notes')
        self.notes = attributes[:'notes']
      end

      if attributes.key?(:'best_for')
        self.best_for = attributes[:'best_for']
      end

      if attributes.key?(:'max_reuse')
        self.max_reuse = attributes[:'max_reuse']
      end

      if attributes.key?(:'add_to_secondary')
        self.add_to_secondary = attributes[:'add_to_secondary']
      end

      if attributes.key?(:'amount_type')
        self.amount_type = attributes[:'amount_type']
      end

      if attributes.key?(:'inventory_amount')
        self.inventory_amount = attributes[:'inventory_amount']
      end

      if attributes.key?(:'archived')
        self.archived = attributes[:'archived']
      end

      if attributes.key?(:'stock_level')
        self.stock_level = attributes[:'stock_level']
      end

      if attributes.key?(:'global_yeast_id')
        self.global_yeast_id = attributes[:'global_yeast_id']
      end

      if attributes.key?(:'is_global')
        self.is_global = attributes[:'is_global']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          deleted == o.deleted &&
          created_on == o.created_on &&
          created_by == o.created_by &&
          modified_on == o.modified_on &&
          modified_by == o.modified_by &&
          name == o.name &&
          product_id == o.product_id &&
          laboratory == o.laboratory &&
          supplier == o.supplier &&
          kegland_product_code == o.kegland_product_code &&
          type == o.type &&
          form == o.form &&
          min_temperature == o.min_temperature &&
          max_temperature == o.max_temperature &&
          flocculation == o.flocculation &&
          attenuation == o.attenuation &&
          notes == o.notes &&
          best_for == o.best_for &&
          max_reuse == o.max_reuse &&
          add_to_secondary == o.add_to_secondary &&
          amount_type == o.amount_type &&
          inventory_amount == o.inventory_amount &&
          archived == o.archived &&
          stock_level == o.stock_level &&
          global_yeast_id == o.global_yeast_id &&
          is_global == o.is_global
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, deleted, created_on, created_by, modified_on, modified_by, name, product_id, laboratory, supplier, kegland_product_code, type, form, min_temperature, max_temperature, flocculation, attenuation, notes, best_for, max_reuse, add_to_secondary, amount_type, inventory_amount, archived, stock_level, global_yeast_id, is_global].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
