=begin
#RAPT API

#Really Awesome Product Technology

The version of the OpenAPI document: v1
Contact: beer@kegland.com.au
Generated by: https://openapi-generator.tech
Generator version: 7.12.0

=end

require 'cgi'

module OpenapiClient
  class CanFillerApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # @param [Hash] opts the optional parameters
    # @option opts [String] :can_filler_id 
    # @return [CanFillerModel]
    def api_can_fillers_get_can_filler_get(opts = {})
      data, _status_code, _headers = api_can_fillers_get_can_filler_get_with_http_info(opts)
      data
    end

    # @param [Hash] opts the optional parameters
    # @option opts [String] :can_filler_id 
    # @return [Array<(CanFillerModel, Integer, Hash)>] CanFillerModel data, response status code and response headers
    def api_can_fillers_get_can_filler_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CanFillerApi.api_can_fillers_get_can_filler_get ...'
      end
      # resource path
      local_var_path = '/api/CanFillers/GetCanFiller'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'canFillerId'] = opts[:'can_filler_id'] if !opts[:'can_filler_id'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'CanFillerModel'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"CanFillerApi.api_can_fillers_get_can_filler_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CanFillerApi#api_can_fillers_get_can_filler_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param [Hash] opts the optional parameters
    # @return [Array<CanFillerModel>]
    def api_can_fillers_get_can_fillers_get(opts = {})
      data, _status_code, _headers = api_can_fillers_get_can_fillers_get_with_http_info(opts)
      data
    end

    # @param [Hash] opts the optional parameters
    # @return [Array<(Array<CanFillerModel>, Integer, Hash)>] Array<CanFillerModel> data, response status code and response headers
    def api_can_fillers_get_can_fillers_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CanFillerApi.api_can_fillers_get_can_fillers_get ...'
      end
      # resource path
      local_var_path = '/api/CanFillers/GetCanFillers'

      # query parameters
      query_params = opts[:query_params] || {}

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<CanFillerModel>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"CanFillerApi.api_can_fillers_get_can_fillers_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CanFillerApi#api_can_fillers_get_can_fillers_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end

    # @param [Hash] opts the optional parameters
    # @option opts [String] :can_filler_id 
    # @option opts [Time] :start_date 
    # @option opts [Time] :end_date 
    # @return [Array<CanFillerTelemetryModel>]
    def api_can_fillers_get_telemetry_get(opts = {})
      data, _status_code, _headers = api_can_fillers_get_telemetry_get_with_http_info(opts)
      data
    end

    # @param [Hash] opts the optional parameters
    # @option opts [String] :can_filler_id 
    # @option opts [Time] :start_date 
    # @option opts [Time] :end_date 
    # @return [Array<(Array<CanFillerTelemetryModel>, Integer, Hash)>] Array<CanFillerTelemetryModel> data, response status code and response headers
    def api_can_fillers_get_telemetry_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: CanFillerApi.api_can_fillers_get_telemetry_get ...'
      end
      # resource path
      local_var_path = '/api/CanFillers/GetTelemetry'

      # query parameters
      query_params = opts[:query_params] || {}
      query_params[:'canFillerId'] = opts[:'can_filler_id'] if !opts[:'can_filler_id'].nil?
      query_params[:'startDate'] = opts[:'start_date'] if !opts[:'start_date'].nil?
      query_params[:'endDate'] = opts[:'end_date'] if !opts[:'end_date'].nil?

      # header parameters
      header_params = opts[:header_params] || {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json']) unless header_params['Accept']

      # form parameters
      form_params = opts[:form_params] || {}

      # http body (model)
      post_body = opts[:debug_body]

      # return_type
      return_type = opts[:debug_return_type] || 'Array<CanFillerTelemetryModel>'

      # auth_names
      auth_names = opts[:debug_auth_names] || ['Bearer']

      new_options = opts.merge(
        :operation => :"CanFillerApi.api_can_fillers_get_telemetry_get",
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => return_type
      )

      data, status_code, headers = @api_client.call_api(:GET, local_var_path, new_options)
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: CanFillerApi#api_can_fillers_get_telemetry_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
